
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR = 5;
  public static final int INI_SOLICITUD = 7;
  public static final int NUEVO_PASSWORD = 21;
  public static final int CREDENCIALES_USUARIO = 16;
  public static final int FIN_SOLICITUD = 8;
  public static final int PUNTOS = 9;
  public static final int ELIMINAR_USUARIO = 24;
  public static final int CREAR_USUARIO = 22;
  public static final int USUARIO_NUEVO = 20;
  public static final int COMA = 15;
  public static final int INI_SOLICITUDES = 2;
  public static final int MAYOR = 4;
  public static final int EOF = 0;
  public static final int EXCLAMACION = 6;
  public static final int PASSWORD = 18;
  public static final int USUARIO = 17;
  public static final int error = 1;
  public static final int FIN_SOLICITUDES = 3;
  public static final int LOGIN_USUARIO = 25;
  public static final int LLAVE_C = 14;
  public static final int CADENA_WS = 10;
  public static final int LLAVE_A = 13;
  public static final int USUARIO_ANTIGUO = 19;
  public static final int CORCHETE_C = 12;
  public static final int MODIFICAR_USUARIO = 23;
  public static final int CORCHETE_A = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INI_SOLICITUDES",
  "FIN_SOLICITUDES",
  "MAYOR",
  "MENOR",
  "EXCLAMACION",
  "INI_SOLICITUD",
  "FIN_SOLICITUD",
  "PUNTOS",
  "CADENA_WS",
  "CORCHETE_A",
  "CORCHETE_C",
  "LLAVE_A",
  "LLAVE_C",
  "COMA",
  "CREDENCIALES_USUARIO",
  "USUARIO",
  "PASSWORD",
  "USUARIO_ANTIGUO",
  "USUARIO_NUEVO",
  "NUEVO_PASSWORD",
  "CREAR_USUARIO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO"
  };
}

